googleGuavaVersion=33.3.1-jre
microsoftAzureMsal4jVersion=1.17.3
auth0JavaJwtVersion=4.4.0
squareupOkhttp3Version=4.11.0
squareupRetrofit2Version=2.11.0
slf4jVersion=2.0.16
eclipseMicroprofileVersion=6.0
eclipseMicroprofileConfigVersion=3.1
smallRyeConfigVersion=3.9.1
osgiAnnotationBundleVersion=2.0.0
jakartaAnnotationVersion=3.0.0
squareupOkhttp3MockwebserverVersion=4.12.0
junitJupiterVersion=5.11.3
mockitoCoreVersion=5.14.2
